### ISSUE TITLE
Extracting roles from messages

### ISSUE THREAD

**Issue by yevgenm** [xtsoukala/dual_path#20]
I have a feeling that the regex in the following line should be slightly changed, otherwise the roles that are followed by contrainsts (e.g., AGENT=pron;) won't be extracted:
https://github.com/xtsoukala/dual_path/blob/18d65bf7f4325ab66c12eec81e4c04ee14a63570/src/modules/corpus_generator.py#L43

Removing the last semicolon may work:
`self.roles = self.structures_df['message'].str.extractall('(;|^)?([A-Z-]*)(=)')[1].unique()`

**Comment by xtsoukala** [comment]
Hi Yevgen, thanks for your comment! You're absolutely right, the original regex wouldn't capture thematic roles that are always followed by a constraint. I had implemented it this way to exclude the event semantics, which I don't consider part of the thematic roles. I've now pushed your suggested edit and I simply exclude "EVENT-SEM" from the roles list. 

Let me know if you need help setting up/replicating an experiment!
Chara
