### ISSUE TITLE
Multiple POS structures per message in structures.csv

### ISSUE THREAD

**Issue by ashnaahmad** [xtsoukala/dual_path#21]
Hi there! I'm using a monolingual English version of this model in my undergraduate thesis. I was just wondering if it would be doable as-is to write multiple possible structures per message in the structures .csv file, and allow the model to use any of the permitted structures when constructing a sentence according to a certain message?

**Comment by xtsoukala** [comment]
Hi Ashna, it's great to hear that you want to run experiments with the Dual-path model! Technically, it is indeed possible to give the same message and pair it with multiple sentence structures, and you can either provide the percentage that you want each (alternative) structure to appear, or you can assign equal probabilities. There's a chance that the automatic evaluation I have in place will mark some sentence alternatives as erroneous, so it's best if you do a manual evaluation of the output. In my research, I chose to assign different event semantics to slightly different structures (e.g., "the boy gives his mother a book" vs "the book gives a book to his mother"), I may have to make the evaluation more flexible. Let me know how it goes and if you encounter any issues.

**Comment by ashnaahmad** [comment]
> 

Thanks so much, that's perfect! I'm actually not super concerned with grammaticality for my particular project (it's a dependency length study) so that should be alright.
